const mongoose = require("mongoose");

const question = mongoose.Schema({
  name: String,
  q: String,
  a: String,
});

const productSchema = mongoose.Schema({
  // //LAPTOP//===============================
  // _id: mongoose.Schema.Types.ObjectId,
  // name: String,
  // price: Number,
  // ean: Number,
  // brand: String,
  // model: String,
  // category: String,
  // cpu: String,
  // cpuDetails: String,
  // gpu: String,
  // gpuDetails: String,
  // ram: String,
  // ramDetails: String,
  // ssd: String,
  // ssdDetails: String,
  // screenSize: String,
  // screenDetails: String,
  // connection: [String],
  // wifi: String,
  // usb: String,
  // bluetooth: String,
  // os: String,
  // finger: String,
  // color: String,
  // weight: String,
  // dimensions: String,
  // backlit: String,
  // battery: String,
  // fastCharge: String,
  // sound: String,
  // webCam: String,
  // warranty: String,
  // cashDiscount: Boolean,
  // lockedPrice: Boolean,
  // productNumber: String,
  // productImage: [String],

  //MOBILE PHONE//=========================
  _id: mongoose.Schema.Types.ObjectId,
  color: String,
  name: String,
  price: Number,
  ean: Number,
  brand: String,
  model: String,
  category: String,
  screenSize: String,
  screenRes: String,
  screenDetails: [String],
  weight: Number,
  build: String,
  os: String,
  chipset: String,
  cpu: String,
  gpu: String,
  ram: String,
  internalMemory: String,
  mainCamera: String,
  mainCameraDetails: String,
  stabilization: String,
  selfieCamera: String,
  selfieCameraDetails: String,
  seansors: [String],
  bluetooth: String,
  gps: String,
  wifi: String,
  usb: String,
  nfc: Boolean,
  radio: Boolean,
  headphones: Boolean,
  infrared: Boolean,
  wirelessCharging: String,
  charging: String,
  battery: String,
  simSlot: String,
  simSlotType: String,
  ip: String,
  dimension: String,
  warranty: String,
  productImage: [String],
  cashDiscount: Boolean,
  lockedPrice: Boolean,
  inWishlist: Boolean,
  questions: [question],
});

module.exports = mongoose.model("Product", productSchema);
