const mongoose = require("mongoose");

const productSchema = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  color: String,
  name: String,
  price: Number,
  ean: Number,
  category: String,
  screenSize: String,
  screenRes: String,
  screenDetails: [String],
  weight: Number,
  build: String,
  os: String,
  chipset: String,
  cpu: String,
  gpu: String,
  ram: String,
  internalMemory: String,
  mainCamera: String,
  mainCameraDetails: String,
  stabilization: String,
  selfieCamera: String,
  selfieCameraDetails: String,
  seansors: [String],
  bluetooth: String,
  gps: String,
  wifi: String,
  usb: String,
  nfc: Boolean,
  radio: Boolean,
  headphones: Boolean,
  infrared: Boolean,
  wirelessCharging: String,
  charging: String,
  battery: String,
  simSlot: String,
  simSlotType: String,
  ip: String,
  dimension: String,
  warranty: String,
  productImage: [String],
});

module.exports = mongoose.model("Product", productSchema);
